# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-09 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20170909_0450'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cover_image',
            field=models.ImageField(blank=True, upload_to='cover_image'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
    ]
